[net]
max_connection = 8
enable_http_proxy=true
enable_static_web_servers=false
[log]
level = "debug"
error_log = "error.log"
access_log = "access.log"

[[entry]]
name = "entry1"

[backend]
back1.host = ""
back2.port = 80


[http]

[error_page]
code500 = "error.html"
code501 = "error.html"
code502 = "error.html"


[[entry]]
name = "entry2"
ip = "127.0.0.1"
port = 80
[[entry3.http.proxy]]
target_host = "http://www.baidu.com"
[[entry3.error_page]]
code500 = "error.html"
code501 = "error.html"
code502 = "error.html"






