[net]
ip = "127.0.0.1"
port = 80
max_thread = 8
enable_http_proxy=true
enable_static_web_servers=false

[[http]]
[[http.servers]]
target_host = "http://www.baidu.com"
[[servers.error_page]]
code500 = "error.html"
code501 = "error.html"
code502 = "error.html"

[[http]]
[[http.servers]]
target_host = "http://www.bilibili.com"
[[servers.error_page]]
code500 = "error.html"
code501 = "error.html"
code502 = "error.html"


[[static_web_servers]]
bind_ip = "127.0.0.1"
port = 80
max_thread = 8
content_type="auto"
date="auto"

[[static_web_servers]]
bind_ip = "127.0.0.1"
port = 80
max_thread = 8
content_type="auto"
date="auto"


[[static_web_servers]]
bind_ip = "127.0.0.1"
port = 80
max_thread = 8
content_type="auto"
date="auto"



